In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
a = pd.read_csv('./Train.csv')
a.head()

feature_1  feature_2  feature_3  feature_4  feature_5     target
0   0.293416  -0.945599  -0.421105   0.406816   0.525662 -82.154667
1  -0.836084  -0.189228  -0.776403  -1.053831   0.597997 -48.897960
2   0.236425   0.132836  -0.147723   0.699854  -0.187364  77.270371
3   0.175312   0.143194  -0.581111  -0.122107  -1.292168  -2.988581
4  -1.693011   0.542712  -2.798729  -0.686723   1.244077 -37.596722

In [8]:
K = pd.read_csv('./Train.csv').values

In [9]:
K

array([[ 2.93416239e-01, -9.45598713e-01, -4.21105147e-01,
         4.06816021e-01,  5.25661832e-01, -8.21546666e+01],
       [-8.36084081e-01, -1.89228039e-01, -7.76402618e-01,
        -1.05383124e+00,  5.97996852e-01, -4.88979602e+01],
       [ 2.36425114e-01,  1.32836018e-01, -1.47722982e-01,
         6.99853963e-01, -1.87364163e-01,  7.72703707e+01],
       ...,
       [ 1.04417694e+00, -8.99206485e-01,  1.73039905e+00,
        -1.87105676e+00,  4.42519647e-01, -1.07510508e+02],
       [-1.26917290e+00, -5.05215916e-03,  1.85766873e+00,
        -1.08036482e+00,  7.36333937e-01, -4.73415578e+01],
       [-1.88400025e+00, -8.49427430e-01, -1.45227035e+00,
         4.88613076e-01,  1.45957580e+00, -1.15939003e+02]])

In [10]:
K.shape

(1600, 6)

In [11]:
X = K[:,:5]
y = K[:, 5]

In [13]:
X

array([[ 0.29341624, -0.94559871, -0.42110515,  0.40681602,  0.52566183],
       [-0.83608408, -0.18922804, -0.77640262, -1.05383124,  0.59799685],
       [ 0.23642511,  0.13283602, -0.14772298,  0.69985396, -0.18736416],
       ...,
       [ 1.04417694, -0.89920649,  1.73039905, -1.87105676,  0.44251965],
       [-1.2691729 , -0.00505216,  1.85766873, -1.08036482,  0.73633394],
       [-1.88400025, -0.84942743, -1.45227035,  0.48861308,  1.4595758 ]])

In [14]:
y

array([ -82.15466656,  -48.89796018,   77.2703707 , ..., -107.51050797,
        -47.34155781, -115.93900296])

In [15]:
X.shape

(1600, 5)

In [16]:
y.shape

(1600,)

## Preprocess - Standardization

In [17]:
mu = X.mean(axis = 0)
mu

array([ 0.0041143 , -0.0276038 , -0.04445943, -0.04240792,  0.01200535])

In [18]:
sig = X.std(axis = 0)
sig

array([0.99702582, 1.02145636, 1.01145129, 1.01687155, 0.97834768])

In [19]:
X = (X-mu)/sig
X

array([[ 0.29016495, -0.89871183, -0.37238147,  0.44177059,  0.52502448],
       [-0.84270473, -0.15822922, -0.72365639, -0.99464217,  0.59896038],
       [ 0.23300381,  0.15706968, -0.10209444,  0.72994655, -0.20378187],
       ...,
       [ 1.0431652 , -0.8532941 ,  1.75476416, -1.79830858,  0.44004223],
       [-1.27708547,  0.02207793,  1.88059294, -1.0207355 ,  0.74035908],
       [-1.89374689, -0.80456069, -1.39187219,  0.52221049,  1.47960738]])

In [20]:
X = np.hstack( (np.ones((X.shape[0],1)) , X)  )
#horziontal concat hstack you can also use concat

In [21]:
X.shape
X

array([[ 1.        ,  0.29016495, -0.89871183, -0.37238147,  0.44177059,
         0.52502448],
       [ 1.        , -0.84270473, -0.15822922, -0.72365639, -0.99464217,
         0.59896038],
       [ 1.        ,  0.23300381,  0.15706968, -0.10209444,  0.72994655,
        -0.20378187],
       ...,
       [ 1.        ,  1.0431652 , -0.8532941 ,  1.75476416, -1.79830858,
         0.44004223],
       [ 1.        , -1.27708547,  0.02207793,  1.88059294, -1.0207355 ,
         0.74035908],
       [ 1.        , -1.89374689, -0.80456069, -1.39187219,  0.52221049,
         1.47960738]])

In [22]:
y = y.reshape(y.shape[0], 1)

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
y.shape

(1600, 1)

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Multivariate Linear Regression

In [71]:
class Linear:
    
    #l.predict
    def predict (self,X, theta):
        """
        X - np array (m, n+1)
        theta - np array (n+1, 1)
        """
    
        return np.dot(X, theta)


    #------------------------------->
    def error(self, X, y, theta):
        """
        params:
            X - np array (m, n+1)
            y - np array(m,1)
            theta - np array(n+1, 1)
        return :
            scalar value = loss value
        """
    
        y_hat = self.predict(X, theta)
        err = np.mean((y_hat - y) **2)
        #can also do sum

        return err
    
    def gradient(self, X, y, theta):
        """
            X - np array (m, n+1)
            y - np array(m,1)
            theta - np array(n+1, 1)
        """
    
        y_hat = self.predict(X, theta)
        grad = np.dot(X.T, (y_hat-y))


        return grad/X.shape[0]
        #grad/m
    
    def fit(self, X, y, lr=0.1, max_itr =100):
    
        theta = np.zeros((X.shape[1],1))
    #     theta (n+1,1)
        error_list = []

        for i in range(max_itr):
            err = self.error(X, y, theta)
            error_list.append(err)

            grad = self.gradient(X, y, theta)

            #updation Rule
            theta = theta -lr*(grad)
        return (theta, error_list)

In [78]:
l = Linear()

In [79]:
opt_theta, error_list = l.fit(X, y)

# full data


In [82]:
new_data = pd.read_csv('./Test.csv').values

In [83]:
new_data.shape

(400, 5)

In [84]:
new_data = (new_data - mu) / sig
new_data = np.hstack( (np.ones((new_data.shape[0],1)) , new_data)  )
new_data.shape

(400, 6)

In [86]:
y_pred = l.predict(new_data, opt_theta)
y_pred

array([[ 1.14582117e+02],
       [ 1.18007905e+02],
       [-2.17378059e+01],
       [-4.39345047e+01],
       [-9.59146698e+01],
       [-4.45104285e+01],
       [-7.55642119e+01],
       [ 2.38226053e+01],
       [ 1.73827481e+02],
       [ 1.72844437e+02],
       [-1.05399158e+02],
       [-2.08000124e+01],
       [-3.91205634e+00],
       [ 1.22991942e+02],
       [ 4.03048407e+01],
       [ 4.57113138e+01],
       [-1.89624739e+02],
       [ 2.26121006e+01],
       [ 1.16413997e+01],
       [ 1.36334464e+02],
       [ 6.49152110e+01],
       [-6.19867449e+01],
       [-1.08192247e+02],
       [-7.41635535e+00],
       [-5.85189671e+01],
       [ 1.18925692e+01],
       [ 2.92358205e+01],
       [ 1.07688152e+02],
       [ 2.41417921e+01],
       [-2.61022995e+01],
       [ 1.10962476e+02],
       [-4.48788442e+01],
       [ 2.16794457e+02],
       [-1.38633732e+01],
       [-2.28596802e+02],
       [ 1.54889287e+02],
       [-2.22926215e+00],
       [ 1.27251390e+01],
       [-3.0